apiVersion: "v1"
appVersion: "[[ .AppVersion ]]"
description: "Chart holding config-controller."
home: "https://github.com/giantswarm/config-controller"
name: "config-controller"
version: "[[ .Version ]]"
annotations:
  application.giantswarm.io/team: "biscuit"
  config.giantswarm.io/version: 1.x.x
